import React, { Component } from "react";

export default class Cinema extends Component {
  render() {
    return (
      <div>
        <div>
          <title>
            Movie Seat Selection Flat Responsive Widget Template :: w3layouts
          </title>
          {/* Index-Page-CSS */}
          <link
            rel="stylesheet"
            href="css/style.css"
            type="text/css"
            media="all"
          />
          {/* //Custom-Stylesheet-Links */}
          {/*fonts */}
          <link
            href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900,900i"
            rel="stylesheet"
          />
          {/* //fonts */}
          {/* Global site tag (gtag.js) - Google Analytics */}
          <meta name="robots" content="noindex" />
          <link rel="stylesheet" href="/assests/css/font-awesome.min.css" />
          {/* New toolbar*/}
          <style
            dangerouslySetInnerHTML={{
              __html:
                '\n* {\n  box-sizing: border-box;\n  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;\n}\n\n\n#w3lDemoBar.w3l-demo-bar {\n  top: 0;\n  right: 0;\n  bottom: 0;\n  z-index: 9999;\n  padding: 40px 5px;\n  padding-top:70px;\n  margin-bottom: 70px;\n  background: #0D1326;\n  border-top-left-radius: 9px;\n  border-bottom-left-radius: 9px;\n}\n\n#w3lDemoBar.w3l-demo-bar a {\n  display: block;\n  color: #e6ebff;\n  text-decoration: none;\n  line-height: 24px;\n  opacity: .6;\n  margin-bottom: 20px;\n  text-align: center;\n}\n\n#w3lDemoBar.w3l-demo-bar span.w3l-icon {\n  display: block;\n}\n\n#w3lDemoBar.w3l-demo-bar a:hover {\n  opacity: 1;\n}\n\n#w3lDemoBar.w3l-demo-bar .w3l-icon svg {\n  color: #e6ebff;\n}\n#w3lDemoBar.w3l-demo-bar .responsive-icons {\n  margin-top: 30px;\n  border-top: 1px solid #41414d;\n  padding-top: 40px;\n}\n#w3lDemoBar.w3l-demo-bar .demo-btns {\n  border-top: 1px solid #41414d;\n  padding-top: 30px;\n}\n#w3lDemoBar.w3l-demo-bar .responsive-icons a span.fa {\n  font-size: 26px;\n}\n#w3lDemoBar.w3l-demo-bar .no-margin-bottom{\n  margin-bottom:0;\n}\n.toggle-right-sidebar span {\n  background: #0D1326;\n  width: 50px;\n  height: 50px;\n  line-height: 50px;\n  text-align: center;\n  color: #e6ebff;\n  border-radius: 50px;\n  font-size: 26px;\n  cursor: pointer;\n  opacity: .5;\n}\n.pull-right {\n  float: right;\n  position: fixed;\n  right: 0px;\n  top: 70px;\n  width: 90px;\n  z-index: 99999;\n  text-align: center;\n}\n/* ============================================================\nRIGHT SIDEBAR SECTION\n============================================================ */\n\n#right-sidebar {\n  width: 90px;\n  position: fixed;\n  height: 100%;\n  z-index: 1000;\n  right: 0px;\n  top: 0;\n  margin-top: 60px;\n  -webkit-transition: all .5s ease-in-out;\n  -moz-transition: all .5s ease-in-out;\n  -o-transition: all .5s ease-in-out;\n  transition: all .5s ease-in-out;\n  overflow-y: auto;\n}\n\n\n/* ============================================================\nRIGHT SIDEBAR TOGGLE SECTION\n============================================================ */\n\n.hide-right-bar-notifications {\n  margin-right: -300px !important;\n  -webkit-transition: all .3s ease-in-out;\n  -moz-transition: all .3s ease-in-out;\n  -o-transition: all .3s ease-in-out;\n  transition: all .3s ease-in-out;\n}\n\n\n\n@media (max-width: 992px) {\n  #w3lDemoBar.w3l-demo-bar a.desktop-mode{\n      display: none;\n\n  }\n}\n@media (max-width: 767px) {\n  #w3lDemoBar.w3l-demo-bar a.tablet-mode{\n      display: none;\n\n  }\n}\n@media (max-width: 568px) {\n  #w3lDemoBar.w3l-demo-bar a.mobile-mode{\n      display: none;\n  }\n  #w3lDemoBar.w3l-demo-bar .responsive-icons {\n      margin-top: 0px;\n      border-top: none;\n      padding-top: 0px;\n  }\n  #right-sidebar,.pull-right {\n      width: 90px;\n  }\n  #w3lDemoBar.w3l-demo-bar .no-margin-bottom-mobile{\n      margin-bottom: 0;\n  }\n}\n',
            }}
          />
          <div className="pull-right toggle-right-sidebar">
            <span className="fa title-open-right-sidebar tooltipstered fa-angle-double-right" />
          </div>
          <div
            id="right-sidebar"
            className="right-sidebar-notifcations nav-collapse"
          >
            <div
              className="bs-example bs-example-tabs right-sidebar-tab-notification"
              data-example-id="togglable-tabs"
            >
              <div id="w3lDemoBar" className="w3l-demo-bar">
                <div className="demo-btns">
                  <a href="https://w3layouts.com/?p=45443">
                    <span className="w3l-icon -back">
                      <span className="fa fa-arrow-left" />
                    </span>
                    <span className="w3l-text">Back</span>
                  </a>
                  <a href="https://w3layouts.com/?p=45443">
                    <span className="w3l-icon -download">
                      <span className="fa fa-download" />
                    </span>
                    <span className="w3l-text">Download</span>
                  </a>
                  <a
                    href="https://w3layouts.com/checkout/?add-to-cart=45443"
                    className="no-margin-bottom-mobile"
                  >
                    <span className="w3l-icon -buy">
                      <span className="fa fa-shopping-cart" />
                    </span>
                    <span className="w3l-text">Buy</span>
                  </a>
                </div>
                {/*-<div class="responsive-icons">
      <a href="#url" class="desktop-mode">
          <span class="w3l-icon -desktop">
              <span class="fa fa-desktop"></span>
          </span>
      </a>
      <a href="#url" class="tablet-mode">
          <span class="w3l-icon -tablet">
              <span class="fa fa-tablet"></span>
          </span>
      </a>
      <a href="#url" class="mobile-mode no-margin-bottom">
          <span class="w3l-icon -mobile">
              <span class="fa fa-mobile"></span>
          </span>
      </a>
  </div>*/}
              </div>
              <div
                className="right-sidebar-panel-content animated fadeInRight"
                tabIndex={5003}
                style={{ overflow: "hidden", outline: "none" }}
              ></div>
            </div>
          </div>
          {/*-728x90-*/}
          <h1>Movie Seat Selection</h1>
          <div className="container">
            <div className="w3ls-reg">
              {/* input fields */}
              <div className="inputForm">
                <h2>fill the required details below and select your seats</h2>
                <div className="mr_agilemain">
                  <div className="agileits-left">
                    <label>
                      {" "}
                      Name
                      <span>*</span>
                    </label>
                    <input type="text" id="Username" required />
                  </div>
                  <div className="agileits-right">
                    <label>
                      {" "}
                      Number of Seats
                      <span>*</span>
                    </label>
                    <input type="number" id="Numseats" required min={1} />
                  </div>
                </div>
                <button onclick="takeData()">Start Selecting</button>
              </div>
              {/* //input fields */}
              {/*-728x90-*/}
              {/* seat availabilty list */}
              <ul className="seat_w3ls">
                <li className="smallBox greenBox">Selected Seat</li>
                <li className="smallBox redBox">Reserved Seat</li>
                <li className="smallBox emptyBox">Empty Seat</li>
              </ul>
              {/* seat availabilty list */}
              {/* seat layout */}
              <div
                className="seatStructure txt-center"
                style={{ overflowX: "auto" }}
              >
                <p id="notification" />
                <table id="seatsBlock">
                  <tbody>
                    <tr>
                      <td />
                      <td>1</td>
                      <td>2</td>
                      <td>3</td>
                      <td>4</td>
                      <td>5</td>
                      <td />
                      <td>6</td>
                      <td>7</td>
                      <td>8</td>
                      <td>9</td>
                      <td>10</td>
                      <td>11</td>
                      <td>12</td>
                    </tr>
                    <tr>
                      <td>A</td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="A1"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="A2"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="A3"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="A4"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="A5"
                        />
                      </td>
                      <td className="seatGap" />
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="A6"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="A7"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="A8"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="A9"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="A10"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="A11"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="A12"
                        />
                      </td>
                    </tr>
                    <tr>
                      <td>B</td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="B1"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="B2"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="B3"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="B4"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="B5"
                        />
                      </td>
                      <td />
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="B6"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="B7"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="B8"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="B9"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="B10"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="B11"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="B12"
                        />
                      </td>
                    </tr>
                    <tr>
                      <td>C</td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="C1"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="C2"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="C3"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="C4"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="C5"
                        />
                      </td>
                      <td />
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="C6"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="C7"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="C8"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="C9"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="C10"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="C11"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="C12"
                        />
                      </td>
                    </tr>
                    <tr>
                      <td>D</td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="D1"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="D2"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="D3"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="D4"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="D5"
                        />
                      </td>
                      <td />
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="D6"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="D7"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="D8"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="D9"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="D10"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="D11"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="D12"
                        />
                      </td>
                    </tr>
                    <tr>
                      <td>E</td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="E1"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="E2"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="E3"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="E4"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="E5"
                        />
                      </td>
                      <td />
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="E6"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="E7"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="E8"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="E9"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="E10"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="E11"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="E12"
                        />
                      </td>
                    </tr>
                    <tr className="seatVGap" />
                    <tr>
                      <td>F</td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="F1"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="F2"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="F3"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="F4"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="F5"
                        />
                      </td>
                      <td />
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="F6"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="F7"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="F8"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="F9"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="F10"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="F11"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="F12"
                        />
                      </td>
                    </tr>
                    <tr>
                      <td>G</td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="G1"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="G2"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="G3"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="G4"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="G5"
                        />
                      </td>
                      <td />
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="G6"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="G7"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="G8"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="G9"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="G10"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="G11"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="G12"
                        />
                      </td>
                    </tr>
                    <tr>
                      <td>H</td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="H1"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="H2"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="H3"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="H4"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="H5"
                        />
                      </td>
                      <td />
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="H6"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="H7"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="H8"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="H9"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="H10"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="H11"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="H12"
                        />
                      </td>
                    </tr>
                    <tr>
                      <td>I</td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="I1"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="I2"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="I3"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="I4"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="I5"
                        />
                      </td>
                      <td />
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="I6"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="I7"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="I8"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="I9"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="I10"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="I11"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="I12"
                        />
                      </td>
                    </tr>
                    <tr>
                      <td>J</td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="J1"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="J2"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="J3"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="J4"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="J5"
                        />
                      </td>
                      <td />
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="J6"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="J7"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="J8"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="J9"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="J10"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="J11"
                        />
                      </td>
                      <td>
                        <input
                          type="checkbox"
                          className="seats"
                          defaultValue="J12"
                        />
                      </td>
                    </tr>
                  </tbody>
                </table>
                <div className="screen">
                  <h2 className="wthree">Screen this way</h2>
                </div>
                <button onclick="updateTextArea()">Confirm Selection</button>
              </div>
              {/* //seat layout */}
              {/* details after booking displayed here */}
              <div
                className="displayerBoxes txt-center"
                style={{ overflowX: "auto" }}
              >
                <table className="Displaytable w3ls-table" width="100%">
                  <tbody>
                    <tr>
                      <th>Name</th>
                      <th>Number of Seats</th>
                      <th>Seats</th>
                    </tr>
                    <tr>
                      <td>
                        <textarea id="nameDisplay" defaultValue={""} />
                      </td>
                      <td>
                        <textarea id="NumberDisplay" defaultValue={""} />
                      </td>
                      <td>
                        <textarea id="seatsDisplay" defaultValue={""} />
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              {/* //details after booking displayed here */}
            </div>
          </div>
          {/*-728x90-*/}
          <div className="copy-wthree">
            <p>© 2018 Movie Seat Selection . All Rights Reserved | Design by</p>
          </div>
          {/* js */}
          {/* //js */}
          {/* script for seat selection */}
          {/* //script for seat selection */}
        </div>
      </div>
    );
  }
}
